const chara = [
    {
        id:1,
        name:'',
        att:{
            str:10,
            con:10,
            dex:10,
            int:10,
            wis:10,
            cha:10
        },
        mod:{
            str:'+0',
            con:'+0',
            dex:'+0',
            int:'+0',
            wis:'+0',
            cha:'+0'
        },
    }
]